# Generated by Django 3.0.5 on 2020-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200523_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='verify',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
