# Generated by Django 3.0.5 on 2020-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200523_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='verify',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
