# Generated by Django 3.0.5 on 2020-05-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200523_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=15),
            preserve_default=False,
        ),
    ]
